# Generated by Django 5.0.6 on 2024-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
            ],
        ),
    ]
